sudo: required
dist: trusty

language: cpp
compiler: gcc

before_install:
  - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
  - chmod +x qt-opensource-linux-x64-5.7.0.run
  - ./qt-opensource-linux-x64-5.7.0.run

script:
  - qmake -config release
  - make -j2