sudo: required
dist: trusty

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - qt5-default
      - libqt5opengl5-dev

script:
  - qmake -config debug
  - make clean
  - make CC=gcc-6 CXX=g++-6 LD=gcc-6 LDX=g++-6 -j2
  - qmake -config release
  - make clean
  - make CC=gcc-6 CXX=g++-6 LD=gcc-6 LDX=g++-6 -j2